name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Configure sysctl limits for Elasticsearch
      run: sudo sysctl -w vm.max_map_count=262144
        
    - name: Run Tests & Generate Jacoco Report
      run: mvn -B verify
      
    - name: Print Test Error Logs
      if: failure()
      run: cat target/surefire-reports/*.txt
      
    - name: Upload Jacoco Coverage Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jacoco-report
        path: target/site/jacoco/
